apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ipmi-exporter","namespace":"ipmi"},"spec":{"ports":[{"port":9290,"protocol":"TCP","targetPort":9290}],"selector":{"app":"ipmi-exporter"}}}
  name: ipmi-exporter
  namespace: ipmi
spec:
  ports:
    - port: 9290
      protocol: TCP
      targetPort: 9290
      name: ipmi
  selector:
    app: ipmi-exporter
  type: ClusterIP
status:
  loadBalancer: {}